version: "3.9"
services:
  vue:
    build: 
      context: ./image-vue
    ports: 
      - 8000:80
  api:
    build:
      context: ./image-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings:ImageDb: "Server=host.docker.internal,${DB_PORT};Database=image_db;User Id=sa;Password=${SA_PASSWORD}"
    ports:
      - 8001:80
  db:
    build:
      context: ./image-db
      args:
        SA_PASSWORD: "${SA_PASSWORD}"
    ports:
      - ${DB_PORT}:1433