SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROCEDURE [dbo].[spUsers_GetByName]
  @username NVARCHAR(100)
AS
BEGIN

  SELECT *
  FROM dbo.Users
  WHERE Username = @username
  FOR JSON PATH, WITHOUT_ARRAY_WRAPPER;

  END
GO
